// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatsAppBusinessPlatform.Infrastucture.Persistence;

#nullable disable

namespace WhatsAppBusinessPlatform.Infrastucture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Contacts.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAAcountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WAAcountId")
                        .IsUnique();

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.MessageStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("MessageReactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PricingCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RawWebhookReqest")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("MessageReactionId");

                    b.ToTable("MessageStatuses", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.StatusError", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId")
                        .IsUnique()
                        .HasFilter("[StatusId] IS NOT NULL");

                    b.ToTable("StatusError", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReactedToMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.HasKey("Id");

                    b.HasIndex("ContactAccountId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ReactedToMessageId");

                    b.ToTable("MessageReaction", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReader", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageReader", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessPhoneId")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("JsonContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("RawWebhookReqest")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContactPhoneNumber");

                    b.HasIndex("ReplyToId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.WAAccounts.WAAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Contacts.Contact", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.WAAccounts.WAAccount", "WAAccount")
                        .WithOne("Contact")
                        .HasForeignKey("WhatsAppBusinessPlatform.Domain.Entities.Contacts.Contact", "WAAcountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WAAccount");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.MessageStatus", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", "Message")
                        .WithMany("Statuses")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReaction", null)
                        .WithMany("Statuses")
                        .HasForeignKey("MessageReactionId");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.StatusError", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.MessageStatus", "Status")
                        .WithOne("Error")
                        .HasForeignKey("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.StatusError", "StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReaction", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.WAAccounts.WAAccount", "ContactAccount")
                        .WithMany("MessageReactions")
                        .HasForeignKey("ContactAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", "Message")
                        .WithOne()
                        .HasForeignKey("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReaction", "MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", "ReactedToMessage")
                        .WithMany("Reactions")
                        .HasForeignKey("ReactedToMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactAccount");

                    b.Navigation("Message");

                    b.Navigation("ReactedToMessage");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReader", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", "Message")
                        .WithMany("MessageReaders")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", b =>
                {
                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.WAAccounts.WAAccount", "WAAccount")
                        .WithMany("Messages")
                        .HasForeignKey("ContactPhoneNumber")
                        .HasPrincipalKey("PhoneNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReplyTo");

                    b.Navigation("WAAccount");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.MessageStatuses.MessageStatus", b =>
                {
                    b.Navigation("Error");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.MessageReaction", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.Messages.WAMessage", b =>
                {
                    b.Navigation("MessageReaders");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("WhatsAppBusinessPlatform.Domain.Entities.WAAccounts.WAAccount", b =>
                {
                    b.Navigation("Contact");

                    b.Navigation("MessageReactions");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
